// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsM_PV1GDz5oN1dLry4xrjlcbu0IIUHK4',
    appId: '1:506069635456:web:c41106b38552962d06f165',
    messagingSenderId: '506069635456',
    projectId: 'listenme-de793',
    authDomain: 'listenme-de793.firebaseapp.com',
    storageBucket: 'listenme-de793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6J7m3gloLd-Of2Hb1qPKPxoiuC65aKtk',
    appId: '1:506069635456:android:d643ababd4acaeee06f165',
    messagingSenderId: '506069635456',
    projectId: 'listenme-de793',
    storageBucket: 'listenme-de793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-lhBbKXFlQmjJNeYtAgXltAP2IdXs0k',
    appId: '1:506069635456:ios:423eed50f806593a06f165',
    messagingSenderId: '506069635456',
    projectId: 'listenme-de793',
    storageBucket: 'listenme-de793.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm-lhBbKXFlQmjJNeYtAgXltAP2IdXs0k',
    appId: '1:506069635456:ios:284d530a3fd8bc6406f165',
    messagingSenderId: '506069635456',
    projectId: 'listenme-de793',
    storageBucket: 'listenme-de793.appspot.com',
    iosBundleId: 'com.example.musicApp.RunnerTests',
  );
}
